name: Format JS/CSS (prettier)

on:
  push:
    branches:
      - "main"
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]


jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout the fork/head-repository and push changes to the fork.
          # If you skip this, the base repository will be checked out and changes
          # will be committed to the base repository!
          repository: ${{ github.event.pull_request.head.repo.full_name }}
  
          # Checkout the branch made in the fork. Will automatically push changes
          # back to this branch.
          ref: ${{ github.head_ref }}

      - name: Install
        run: yarn install
        env:
          CI: true

      - name: Run prettier CSS
        run: yarn run prettier --write '*.{css}'

      - name: Run prettier JS
        run: yarn run prettier --write '*.{js}'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          file_pattern: '*.css, *.js'
          
