name: Format JS/CSS (prettier)

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**.css"
      - "**.js"
jobs:
  prettier:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: yarn install
        env:
          CI: true

      - name: Run prettier CSS
        run: yarn run prettier --write 'css/*.{css}'

      - name: Run prettier JS
        run: yarn run prettier --write 'js/*.{js}'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
